---
services:
  luigi-randomusers:
    build:
      context: .
      dockerfile: services/luigi-randomusers/Dockerfile
    environment:
      - N_RECORD=100
      - SLEEP_SECS=30
    volumes:
      - ./luigi-output:/home/default/clickhouse-randomuser/src/luigi-output
    networks:
      - ch_net
    depends_on:
      - clickhouse-server

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.8-alpine
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - ch_net

networks:
  ch_net:
...
